# Unique name for this workflow
name: CI

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - main

# Jobs to be executed
jobs:
    format-lint-lwc-tests:
        runs-on: ubuntu-latest
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            # Check for hardcoded username in XP cloud config
            - name: 'Check for hardcoded username in XP cloud config'
              run: |
                  fileToCheck="cc-site/main/default/sites/Coral_Cloud.site-meta.xml"
                  if grep -q siteAdmin $fileToCheck; then
                      echo "siteAdmin tag detected in $fileToCheck. Remove the tag to fix this.";
                      exit 1;
                  fi
                  if grep -q siteGuestRecordDefaultOwner $fileToCheck; then
                      echo "siteGuestRecordDefaultOwner tag detected in $fileToCheck. Remove the tag to fix this.";
                      exit 1;
                  fi

            # Install Volta to enforce proper node and package manager versions
            - name: 'Install Volta'
              uses: volta-cli/action@v4

            # Cache node_modules to speed up the process
            - name: 'Restore node_modules cache'
              id: cache-npm
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: HUSKY=0 npm ci

            # LWC unit tests
            - name: 'Unit test Lightning Web Components'
              run: npm run test:unit:coverage

            - name: Archive code coverage results
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage-report
                path: ./coverage
